server:
  port: 8084

spring:
  application:
    name: SEARCH-SERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/moveAuth

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5000
    socket-timeout: 60000

  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # Servlet Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # Cloud Configuration
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      retry:
        enabled: true

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10

# JWT Configuration
jwt:
  secret: bW92ZVNlY3JldEtleTg3MzI0ODczMjRzZGpmaHNqa2FoZjM0OTg3MzQwOTg3c2Rmc2RpdWg0ODczMjQ=
  expiration: 43200000  # 12 hours
  refresh-expiration: 2592000000  # 30 days

# CORS Configuration
cors:
  allowed-origins: "http://localhost:4200,http://localhost:3000,http://localhost:8080"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
  allowed-headers: "Authorization,Content-Type,Accept,Origin,X-Requested-With,X-Auth-User,X-Auth-Roles"
  exposed-headers: "Authorization,X-Auth-User,X-Auth-Roles"
  allow-credentials: true
  max-age: 3600

# RabbitMQ Event Routing for Content Service Events
content:
  events:
    exchange: content.events.exchange
    content-created-routing-key: content.created
    content-updated-routing-key: content.updated
    content-deleted-routing-key: content.deleted
    content-created-queue: content.created.queue
    content-updated-queue: content.updated.queue
    content-deleted-queue: content.deleted.queue

# Elasticsearch Indices Configuration
elasticsearch:
  indices:
    content-index: move_contents
    location-index: move_locations

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.move.searchservice: DEBUG
    org.springframework.data.elasticsearch: DEBUG
    org.elasticsearch: INFO
recommendation:
  fastapi:
    host: 127.0.0.1
    port: 8000
    path: /recommend
